stages:          # List of stages for jobs, and their order of execution
  - test

include:
    - template: Code-Quality.gitlab-ci.yml

code_quality:
    stage: test
    artifacts:
        paths: [gl-code-quality-report.json]
