stages:          # List of stages for jobs, and their order of execution
  - test

include:
    - template: Code-Quality.gitlab-ci.yml

code_quality:
    stage: test
    artifacts:
        paths: [gl-code-quality-report.json]

code_quality_html:
  extends: code_quality
  variables:
    REPORT_FORMAT: html
  artifacts:
    paths: [gl-code-quality-report.html]
