stages:          # List of stages for jobs, and their order of execution
  - test

include:
    - template: Code-Quality.gitlab-ci.yml

code_quality:
    stage: test
    artifacts:
        paths: [gl-code-quality-report.json]

mypy:
    stage: test
    image: python:3.7
    script:
        - pip install mypy --quiet
        - pip install -e .
        - mypy m4i_data_management
    artifacts:
        paths: [mypy-report.json]